In [1]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [32]:
data_dict = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data_dict)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [12]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns

In [17]:
df["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [16]:
df["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [18]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [51]:
df["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

Removing columns

In [52]:
df.drop("Designation", axis = 1) # by default axis is 0
# now if you have to remove from main data then add inplace = True

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [53]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [54]:
df.drop("Designation", axis=1, inplace=True)

In [55]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
df.drop(0)
# now if you have to remove from main data then add inplace = True

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [56]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [57]:
df.drop(0, inplace=True)

In [58]:
df

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [59]:
df.drop(["City", "Salary"], axis=1)

    Name  Age
1   Anna   34
2  Peter   29
3  Linda   42

Selecting rows

In [61]:
df

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [65]:
df.loc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [68]:
df.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [70]:
df.iloc[2] # selecting index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [72]:
df.loc[[1,2]][["Name", "Salary"]]

    Name  Salary
1   Anna   70000
2  Peter   62000

Conditional selection

In [81]:
df

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [80]:
df[df['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [85]:
df[(df['Age'] > 30) & (df["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000